# 将静态内容部署到 GitHub Pages 的简易工作流程
name: Deploy static content to Pages

on:
  # 仅在推送到默认分支时运行。
  push:
    branches: ['knitpage']

  # 这个选项可以使你手动在 Action tab 页面触发工作流
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages。
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发的部署
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 单次部署的工作描述
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        # id: deployment
        # uses: actions/deploy-pages@v4
        run: |
          # 配置 git 用户信息
          git config --global user.name "Arashitake"
          git config --global user.email "1292795269@qq.com"

          # 克隆 gh-pages 分支
          git clone --single-branch --branch gh-pages https://github.com/Arashitake/knitModel.git gh-pages

          # 复制构建后的文件到 gh-pages 分支目录
          cp -r ./dist/* gh-pages/

          # 提交并推送更改
          cd gh-pages
          git add .
          git commit -m 'Deploy static content to GitHub Pages'
          git push origin gh-pages
