name: Sync Folder to Target Branch

on:
  push:
    branches:
      - master # 监视主分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Configure Git
        run: |
          git config --global user.name "Arashitake"
          git config --global user.email "1292795269@qq.com"

      - name: Deploy
        # 使用别人写好的一个 action
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: knitpage
          # 部署目录为 VuePress 的默认输出目录
          build_dir: KnitModel01
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
