name: Sync Folder to Target Branch

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Configure Git
        run: |
          git config --global user.name "Arashitake"
          git config --global user.email "1292795269@qq.com"

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: knitpage
          build_dir: KnitModel01
        env:
          GITHUB_TOKEN: ${{ secrets.knit }}
